# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

# Fix for application is damaged error
# - Copy app to applications folder
# - Run in terminal: sudo xattr -cr img2h.app
# See: https://github.com/archimatetool/archi/issues/555#issuecomment-554965144
# for details.

name: Build macOS Installer

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
          distribution: 'adopt'
      - name: Build with Maven
        run: ./mvnw -B clean install -P mkinstaller
      - name: Update Automatic Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{secrets.GITHUB_TOKEN}}"
          automatic_release_tag: "macOS-latest"
          prerelease: true
          title: "macOS Development Build"
          files: ./gui/target/*.dmg
