# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build Unix Installer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
        distribution: 'adopt'
    - name: Build with Maven
      run: ./mvnw -B clean install -P mkinstaller
    - name: Update Automatic Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{secrets.GITHUB_TOKEN}}"
        automatic_release_tag: "Ubuntu-latest"
        prerelease: true
        title: "Ubuntu Development Build"
        files: ./gui/target/*.deb
