# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build Unix Installer

on:
  workflow_run:
    workflows: ["Build and run tests (CI)"]
    branches: ["main"]
    types:
      - completed

jobs:
  build:
    # Run only if main workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
        distribution: 'adopt'
    - name: "Modularize dependencies"
      run: ./build-modularized-version-of-dependencies.sh
    - name: "Build with Maven"
      run: ./mvnw -B clean install -P mkinstaller
    - name: "Update Automatic Release"
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{secrets.GITHUB_TOKEN}}"
        automatic_release_tag: "Ubuntu-latest"
        prerelease: false
        title: "Ubuntu Development Build"
        files: ./gui/target/*.deb
